### ISSUE TITLE
Context demos needed

### ISSUE THREAD

**Issue by gdamore** [nanomsg/mangos-v2#46]
We have this cool new context API, but there are no demo programs!

Probably we should follow the example of NNG here.

**Comment by lobocv** [comment]
I've started working on this. Should have something soon :)

**Comment by gdamore** [comment]
Oh, also, you should add yourself to the AUTHORS file.

**Comment by lobocv** [comment]
Thanks, will do.
So I pushed up my latest changes with the random sleep in the workers.. but I couldn't get it to work!
It works without the sleep. I'm wondering if I uncovered a bug of some sort?

**Comment by gdamore** [comment]
I’ll take a look — its possible you did!
