### ISSUE TITLE
PipeEventAttaching

### ISSUE THREAD

**Issue by SysLabIT** [nanomsg/mangos-v2#84]
Hi,

I noticed that such a mechanism is described:

> // PipeEventAttaching is called before the Pipe is registered with the
> // socket.  The intention is to permit the application to reject
> // a pipe before it is attached.

Therefore, I wonder if the correct way to reject the client looks like this:
```
func pipeEventHook(action mangos.PipeEvent, pipe mangos.Pipe) {
   if action == mangos.PipeEventAttaching {
      pipe.close()
   }
}
```

If so, then why the client at the other end of the pipe receives the event PipeEventAttached?
Of course, he receives PipeEventDetached a moment later.
Nevertheless, it seems to me that it should not Attach in such a configuration in the first place.

Another thought.
I know I can get a remote IP and port of the client that is trying to Attache, to pipe.
Is there any other way to identify the client that connects to the server?

It would be ideal to have something like Hello msg. Message that is sent during Dial. 
Without it, until client sends the first message, server knows who he is.

**Comment by gdamore** [comment]
Unfortunately, you are misunderstanding.  The pipe attach event is done after a TCP connection is already established, and indeed after the initial handshake is performed.

We might want to change this (for other reasons), but the basic wire protocol will be unchanged.

If you need richer details about the client, you might want to look at using TLS certificates or something like that, which can be obtained from the pipe.  Alternatively you can set up some application layer protocol to pass whatever identity information you want.

**Comment by SysLabIT** [comment]
Because the traffic between the client and the server takes place through ZeroTier Network, I would not really like to use another TLS.

Where is in the best place to get information about the new client?
When receive a new message?
Eg. in the Req/Res model

Do I need to attach the identity of the sender to each message?
Or Is there a way to determine that this is another message from a known sender?

I noticed that I can not rely on RemotAddr, because with network isses the Mangos can do reconnect client to other port.
Maybe I can use Pipe.ID() for this?

**Comment by gdamore** [comment]
Pipe ID doesn't tell you anything about the peer.  The only way to really be sure is to use an authenticated connection.  TLS is the best option for mangos users at present.  (NNG does have a ZeroTier transport as an alternative, but that isn't Go code.)

**Comment by SysLabIT** [comment]
Thank you.
