### ISSUE TITLE
Cross Req/Res timeout

### ISSUE THREAD

**Issue by SysLabIT** [nanomsg/mangos-v2#85]
Hi,

I encountered a very strange case.
There are two processes / programs on one host.
First have xrep socket on port 3001 (to revice msg and reply) and req (to send msg)
Second have xrep socket on port 3002 (to revice msg and reply) and req (to send msg)

So that the first can send a Req to the second and recv XRep.
And independently the second one can send a Req to the first.

If only the first sends and the second responds, then everything is fine.

If only the second sends and the first responds, then everything is fine.

But if the first send and receive a reply.
After which the second one wants to send something, he receives a timeout.
From this moment, the first pipe works correctly.
The second one connects, I see the PipeEventAttached on both sides and after timeout PipeEventDetached. However, no message passes.

If I change the order of sending and the second sends the message first, then the second pipe has the same problem.

**Comment by gdamore** [comment]
I think I need example code to understand what exactly is happening here.  My guess is there is somehting wrong with how you are setting up your connections.

**Comment by SysLabIT** [comment]
I rewritten the code with Context and the issue disappeared. I assume that I made a mistake in the code.
