### ISSUE TITLE
no matching versions for query "latest"

### ISSUE THREAD

**Issue by AsynchronousResource** [nanomsg/mangos-v2#86]
go version go1.11 darwin/amd64

I have a module and when I try to do "go get" for mangos as follows:
go get nanomsg.org/go/mangos/v2
I get the following error:
go get nanomsg.org/go/mangos/v2: no matching versions for query "latest"

**Comment by gdamore** [comment]
This is a duplicate of #78 … I will be fixing this shortly.  Probably mangos will getting yet another import path, with v3.  Stay tuned.

**Comment by AsynchronousResource** [comment]
Thanks!
